package model.enums;

public enum Request {
    login,
    getClients,
    getSubusersAllowed,
    getSubusersCreated,
    createEmptyClient,
    modifyClientForCreation,
    createEmptyDebt,
    modifyDebtForCreation,
    recordDeposit,
    modifyDebt,
    modifyUser,
    verifyPassword,
    changePassword,
    verifyUsernameExistence,
    addSubuser,
    disableSubuser,
    enableSubuser,
    modifyGeneralInfo,
    getCashInRegister,
    getDepositClients,
    getUserInfo,
    getAssociatedUsers,
    disableClient,
    getClientDebts,
    getClientDeposits,
    voidDeposit,
    getDebtTotalLinkedDeposits,
    voidDebt,
    requestPasswordReset,
    verifyToken,
    verifyPhoneExistence,
    verifyEmailExistence,
    verifyUpdated
}
